# Generated by Django 3.2.4 on 2021-07-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
        migrations.AlterModelTable(
            name='barn',
            table='barn',
        ),
        migrations.AlterModelTable(
            name='breed',
            table='breed',
        ),
        migrations.AlterModelTable(
            name='calving',
            table='calving',
        ),
        migrations.AlterModelTable(
            name='gender',
            table='gender',
        ),
        migrations.AlterModelTable(
            name='insemination',
            table='insemination',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='pregnancycheck',
            table='pregnancycheck',
        ),
        migrations.AlterModelTable(
            name='seedingtype',
            table='seedingtype',
        ),
        migrations.AlterModelTable(
            name='weight',
            table='weight',
        ),
    ]
