# Generated by Django 3.2.4 on 2021-07-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finliveapp', '0002_auto_20210701_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentid', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('mixing_date', models.DateField()),
                ('fresh_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dry_matter_content', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'feed',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'laboratory',
            },
        ),
        migrations.RenameField(
            model_name='insemination',
            old_name='inseminationmethod',
            new_name='insemination_method',
        ),
        migrations.AddField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animal',
            name='rfid',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='calving',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization'),
        ),
        migrations.AddField(
            model_name='insemination',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization'),
        ),
        migrations.AddField(
            model_name='pregnancycheck',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization'),
        ),
        migrations.AddField(
            model_name='weight',
            name='equipment_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='weight',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization'),
        ),
        migrations.CreateModel(
            name='MilkingSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finliveapp.barn')),
                ('equipment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finliveapp.organization')),
            ],
            options={
                'db_table': 'milking_system',
            },
        ),
        migrations.CreateModel(
            name='Milking_Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_milk_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('rf_milk', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rb_milk', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('lf_milk', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('lb_milk', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('rf_conductivity', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('rb_conductivity', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('lf_conductivity', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('lb_conductivity', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('somatic_cell_count', models.IntegerField(null=True)),
                ('colour', models.CharField(max_length=64, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total_flow_duration', models.IntegerField(null=True)),
                ('rf_flow_duration', models.IntegerField(null=True)),
                ('rb_flow_duration', models.IntegerField(null=True)),
                ('lf_flow_duration', models.IntegerField(null=True)),
                ('lb_flow_duration', models.IntegerField(null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finliveapp.animal')),
                ('barn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finliveapp.barn')),
                ('milking_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.milkingsystem')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization')),
            ],
            options={
                'db_table': 'milking_event',
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_start_time', models.DateTimeField()),
                ('visit_end_time', models.DateTimeField(null=True)),
                ('visit_duration', models.IntegerField(blank=True, null=True)),
                ('feed_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('feed_consumption', models.DecimalField(decimal_places=3, max_digits=6)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finliveapp.animal')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.equipment')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.feed')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization')),
            ],
            options={
                'db_table': 'feeding',
            },
        ),
        migrations.CreateModel(
            name='FeedAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=256)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('analysis_number', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('experiment_number', models.CharField(max_length=128)),
                ('sample_start_date', models.DateField()),
                ('sample_end_date', models.DateField(null=True)),
                ('primary_dry_matter', models.IntegerField(null=True)),
                ('secondary_dry_substance', models.IntegerField(null=True)),
                ('ash_content', models.IntegerField(null=True)),
                ('crude_protein', models.IntegerField(null=True)),
                ('fat', models.IntegerField(null=True)),
                ('ndf', models.IntegerField(null=True)),
                ('indf', models.IntegerField(null=True)),
                ('adf', models.IntegerField(null=True)),
                ('starch', models.IntegerField(null=True)),
                ('aia', models.IntegerField(null=True)),
                ('cellulase_solubility', models.IntegerField(null=True)),
                ('digestivity', models.IntegerField(null=True)),
                ('d_value', models.IntegerField(null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nh3_n', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ethanol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_n', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lactic_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acetic_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('propionic_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('butyric_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isobutyric_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isovaleric_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capronic_acid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.feed')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.laboratory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization')),
            ],
            options={
                'db_table': 'feed_analysis',
            },
        ),
    ]
