# Generated by Django 3.2.4 on 2021-07-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0004_auto_20210721_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='birthDate',
            new_name='birthdate',
        ),
    ]
