# Generated by Django 3.2.4 on 2021-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0006_alter_calving_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calving',
            name='assistance',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
