# Generated by Django 3.2.4 on 2021-08-30 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0007_alter_calving_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='apikey',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animalid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='euid',
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('euid', 'organization'), name='euid_organization_unique'),
        ),
    ]
