# Generated by Django 3.2.4 on 2021-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0008_auto_20210830_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
