# Generated by Django 3.2.4 on 2021-09-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0011_auto_20210910_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkingsystem',
            old_name='equipment_id',
            new_name='equipment',
        ),
        migrations.AddField(
            model_name='feed',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.organization'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentid',
            field=models.CharField(max_length=64),
        ),
    ]
