# Generated by Django 3.2.4 on 2021-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0013_auto_20211001_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_id',
        ),
        migrations.AddField(
            model_name='feed',
            name='feedid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
