# Generated by Django 3.2.4 on 2021-10-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0014_auto_20211004_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='barn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.barn'),
        ),
    ]
