# Generated by Django 3.2.4 on 2021-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0015_feeding_barn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animalid',
            field=models.IntegerField(),
        ),
    ]
