# Generated by Django 3.2.4 on 2021-10-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0016_alter_animal_animalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milking_event',
            name='somatic_cell_count',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
