# Generated by Django 3.2.4 on 2021-10-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0018_organizationapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='apikey',
        ),
    ]
