# Generated by Django 3.2.4 on 2021-11-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0019_remove_organization_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasmeasurement',
            old_name='equipmentid',
            new_name='equipment',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='equipment_id',
        ),
        migrations.AddField(
            model_name='barn',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='barn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finliveapp.barn'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milkingsystem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seedingtype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finliveapp.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
