# Generated by Django 3.2.4 on 2021-11-10 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0021_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
