# Generated by Django 3.2.4 on 2021-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0022_alter_equipment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
