# Generated by Django 3.2.4 on 2021-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0024_gassystem_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='feed_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.UniqueConstraint(fields=('animal', 'visit_start_time'), name='unique visit'),
        ),
    ]
