# Generated by Django 3.2.4 on 2021-12-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finliveapp', '0025_auto_20211210_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasmeasurement',
            name='euid',
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='airflow',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='airflow_cf',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='barn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finliveapp.barn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='wind_cf',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='ch4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='co2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_measurement_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='h2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_measurement_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasmeasurement',
            name='o2',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='gasmeasurement',
            table='gas_measurement',
        ),
    ]
