# Generated by Django 3.2.4 on 2021-12-14 10:40

from django.db import migrations, models

from finliveapp.models import GasMeasurement


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0026_auto_20211214_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasmeasurement',
            name='wind_direction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
