# Generated by Django 3.2.4 on 2021-12-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0027_gassystem_wind_direction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gasmeasurement',
            constraint=models.UniqueConstraint(fields=('equipment', 'start_time'), name='unique gas measurement'),
        ),
    ]
