# Generated by Django 3.2.4 on 2021-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0028_gasmeasurement_unique gas measurement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feeding',
            name='unique visit',
        ),
        migrations.RenameField(
            model_name='feeding',
            old_name='visit_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='feeding',
            old_name='visit_start_time',
            new_name='start_time',
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.UniqueConstraint(fields=('animal', 'start_time'), name='unique visit'),
        ),
    ]
