# Generated by Django 3.2.4 on 2021-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finliveapp', '0030_alter_animal_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
    ]
